### ISSUE TITLE
rTorrent Watcher; XMLRPC API

### ISSUE THREAD

**Issue by MagnaCapax** [MagnaCapax/PMSS#16]
Sometimes rTorrent remains fully functionally other than XMLRPC API, hence rutorrent not responding.

We need something to check for this, just like ruTorrent, and restart rTorrent if it remains unresponsive via xmlrpc.

**Comment by MagnaCapax** [comment]
This looks implemented on `main` in the last 1–2 weeks:

- `c6be86b` (2026-01-26): adds an rTorrent SCGI/XMLRPC health check in `scripts/cron/checkRtorrent.php`, plus new helpers under `scripts/lib/rtorrent/` and hermetic tests.
- `62e4921` (2026-01-26): fixes watchdog rTorrent process detection (anchored `pgrep`).
- `c40b171` / `8ef4344` (2026-01-28): additional rTorrent rc/template hardening after start failures.

Proposing `complete-verify`: please confirm on a host that when rTorrent’s XMLRPC/SCGI stalls (ruTorrent becomes unresponsive), the watchdog detects it and recovers cleanly (restart/quarantine behavior as intended). Operator can close once verified.

**Comment by MagnaCapax** [comment]
## Verified Working

Tested on `<hostname>` (git/main@2026-01-31 07:39), AMD Opteron 2419 EE (6-core, 2008), Debian 12.13.

### Phase 1: Organic Watchdog Observation

The SCGI watchdog was observed actively handling real unresponsive users during testing:

| Time (UTC) | Event |
|---|---|
| 07:38:08 | SCGI unresponsive detected for 2 users; state files created |
| 07:39:45 | Manual debug run confirms `age=102s`, grace period holding |
| 07:40:09 | Cron fires, `age=121s` > 120s threshold → **restart triggered** |
| 07:40:17 | Old processes killed, new executor started |
| 07:40:17 | Custom `.rtorrent.rc.custom` quarantined after repeated failures |

### Phase 2: Controlled Test

Created test account with 8 Linux ISO torrents loaded (Ubuntu, Fedora, Arch, Mint), throttled to 10KB/s.

**SCGI Baseline:**
- `system.api_version` ping: **0.5ms**
- `d.multicall2` (8 torrents, 7 fields): **0.8ms**
- 5 sequential pings: **1ms total** (all pass)

**Stall Test (socket rename to simulate unresponsive):**

| Time (UTC) | Event |
|---|---|
| 07:44:05 | Socket renamed → SCGI unresponsive confirmed |
| 07:44:30 | Manual watchdog run → "observing", state file created |
| 07:46 | Cron run → `age < 120s` → grace period holding |
| 07:48:05 | Cron run → `age=215s > 120s` → **restart triggered** |
| 07:48:05 | SIGTERM → 3s → SIGKILL → old PID killed |
| 07:48:10 | startRtorrent → new SCREEN + executor + rtorrent PID |
| 07:48:13 | New socket created, **SCGI responsive** |

**All verified:**
- [x] SCGI unresponsive detection works (socket missing/timeout)
- [x] 120s grace period prevents false positives
- [x] Restart sequence: SIGTERM → SIGKILL → startRtorrent
- [x] Process before/after snapshots logged
- [x] Custom config quarantine works
- [x] New instance starts cleanly with fresh socket
- [x] SCGI responsive post-recovery
- [x] No impact on other users' rtorrent instances

**Process count analysis:** 73 total `ps | grep rtorrent` matches = normal (4 per user × 18 users: SCREEN + PHP executor + sh + rtorrent binary). No duplicates.

Test user terminated, all artifacts cleaned.

Väinämöinen <noreply@pulsedmedia.com>

**Comment by MagnaCapax** [comment]
## Stress Test Methodology

### Test Environment Setup

1. **Created test account** on production server (256MB RAM quota, 10GB disk):
   ```
   php /scripts/addUser.php <testuser> <password> 256 10
   ```

2. **Loaded 8 Linux ISO torrents** (Ubuntu 22.04, Fedora 41, Arch, Mint) via XMLRPC `load.raw_start`:
   - Torrents downloaded from official distro sites to `/tmp/`, validated with `file` command
   - Loaded via PHP SCGI calls to the test user's Unix socket

3. **Throttled to 10KB/s** to keep load minimal:
   ```
   throttle.global_down.max_rate.set = 10240
   throttle.global_up.max_rate.set = 10240
   ```

### SCGI Baseline Measurement

Verified SCGI responsiveness under normal load before stalling:

| Test | Method | Result |
|---|---|---|
| Health ping | `system.api_version` (same call the watchdog uses) | 0.5ms |
| Heavy query | `d.multicall2` — 8 torrents × 7 fields | 0.8ms |
| Burst | 5 sequential `system.api_version` pings | 1ms total |

### Stall Method: Socket Rename

**Why not XMLRPC hammering?** rTorrent's single-threaded event loop processes SCGI requests synchronously, so parallel `d.multicall2` calls serialize. In theory, sustained concurrent requests should block the event loop. In practice, on a local Unix socket with only 8 torrents, each request completes in <1ms — sustaining a stall for >120s requires maintaining hundreds of parallel connections, which is fragile and risks affecting other users' CPU time on a production box.

**Chosen method:** Renaming the Unix socket simulates the exact condition the watchdog detects — the socket path exists in the rtorrent config but is unreachable from the filesystem. This is functionally equivalent to a stalled/hung rtorrent that stops accepting connections, which is the real-world failure mode #16 was filed for.

```
mv /home/<user>/.rtorrent.socket /home/<user>/.rtorrent.socket.bak
```

- rtorrent process stays alive (PID unchanged)
- Socket inode still exists in kernel but path is gone
- `rtorrentScgiPing()` returns false (same as a truly hung instance)
- Watchdog cannot distinguish this from a real SCGI hang — both fail the same `fsockopen()` + `system.api_version` check

### What Was Verified

1. **Detection path**: `checkRtorrent.php` iterates users via `listUsers.php`, checks process existence via `rtorrentProcessPgrepExact()`, then runs `rtorrentScgiPing()` on the socket path. Failure creates a state file in `/run/pmss/`.

2. **Grace period**: State file stores the unix timestamp of first detection. Subsequent runs compare `time() - firstSeen` against the 120s threshold. The watchdog correctly held during the grace window (`age=102s` → "waiting") and only triggered after expiry (`age=215s` → "stale").

3. **Restart sequence**: `rtorrentProcessRestart()` → SIGTERM to rtorrent + executor PIDs → sleep 3s → re-check survivors → SIGKILL → sleep 1s → `/scripts/startRtorrent <user>`. Process snapshots logged before and after.

4. **Custom config quarantine**: When rtorrent fails to start after restart, the watchdog quarantines `.rtorrent.rc.custom` (atomic rename to `.broken-TIMESTAMP-PID`) and retries without it.

5. **Recovery**: New rtorrent process creates a fresh Unix socket. `rtorrentScgiPing()` returns true. State file cleared.

Väinämöinen <noreply@pulsedmedia.com>
